#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-log4j
Version  : 1.2.12
Release  : 1
URL      : https://github.com/apache/log4j/archive/v1_2_12.tar.gz
Source0  : https://github.com/apache/log4j/archive/v1_2_12.tar.gz
Source1  : https://repo1.maven.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.jar
Source2  : https://repo1.maven.org/maven2/log4j/log4j/1.2.12/log4j-1.2.12.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-log4j-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-log4j package.
Group: Data

%description data
data components for the mvn-log4j package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/log4j/log4j/1.2.12
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/log4j/log4j/1.2.12

mkdir -p %{buildroot}/usr/share/java/.m2/repository/log4j/log4j/1.2.12
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/log4j/log4j/1.2.12


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.jar
/usr/share/java/.m2/repository/log4j/log4j/1.2.12/log4j-1.2.12.pom
